name: Deploying with Maven

on: 
  push:
    branches: 
      - 'dev-github-actions'
    # paths-ignore:
    #   - '.github/workflows/*'
  
  pull_request:
    branches: 
      - 'main' 


jobs:
  test:
    strategy: 
      matrix:
        java-versions: [8, 17]
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-versions }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Running tests with Maven...
      run: mvn test
  lint:
    strategy: 
      matrix:
        java-versions: [8, 17]
        os: [ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-versions }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Linting with Checkstyle
      run: mvn clean checkstyle:check
  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Building with Maven...
      run: mvn -B clean package
    - name: Upload Artifacts. 
      uses: actions/upload-artifact@v3
      with:
        path: target
        name: build-files
    - name: Download Artifacts. 
      uses: actions/download-artifact@v3
      with:
        name: build-files
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: user/app:latest
    
