name: Java testing with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Building with Maven...
      run: mvn -B clean package

    - name: Running tests with Maven...
      run: mvn test