name: Deploying with Maven

on: 
  push:
    branches: 
      - 'dev-github-actions'
  
  pull_request:
    branches: 
      - 'main' 


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Running tests with Maven...
      run: mvn test
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Linting with Checkstyle
      run: mvn clean checkstyle:check
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Building with Maven...
      run: mvn -B clean package
